@startuml Project Management Use Cases

left to right direction

actor DM

actor User

database Server

package Project {
    (Make a new project) as make_a_project
    (Open an existing project) as open_a_project
}

DM --> make_a_project
DM --> open_a_project

User --> open_a_project

make_a_project --> Server
open_a_project --> Server

@enduml


@startuml Project Mode Use Cases

left to right direction

actor DM

actor User

database Server

package Project{
    (See polygon descriptions) as see_polygon_decriptions
    (Create new polygons) as create_new_polygons
    (Create new nodes) as create_new_nodes
    (Move or Delete existing nodes) as manage_existing_nodes
}

User --> see_polygon_decriptions
DM --> see_polygon_decriptions

User --> create_new_polygons
DM --> create_new_polygons

DM --> create_new_nodes

DM --> manage_existing_nodes

see_polygon_decriptions --> Server
create_new_polygons --> Server
create_new_nodes --> Server
manage_existing_nodes --> Server

@enduml